require("smoothvim.config.core")
require("smoothvim.config.keymaps")
require("smoothvim.config.theme")
require("smoothvim.config.lsp")
require("smoothvim.config.autocmds")
-- require("smoothvim.config.cmp")
-- require("smoothvim.config.formatter")
-- require("smoothvim.config.lint")
