require("smoothvim.plugins.mason")
require("smoothvim.plugins.git")
require("smoothvim.plugins.colors")
require("smoothvim.plugins.neotree")
require("smoothvim.plugins.trouble")
require("smoothvim.plugins.lualine")
require("smoothvim.plugins.telescope")
require("smoothvim.plugins.treesitter")
require("smoothvim.plugins.fidget")
-- require("smoothvim.plugins.lsp")
require("smoothvim.plugins.comments")
require("smoothvim.plugins.autopairs")
require("smoothvim.plugins.autotag")
require("smoothvim.plugins.test")
